"""build_page.py — convert content/bluffers_guide.md to pages/2_Bluffers_Guide.py.

Markdown format:
  ## Heading        → st.subheader("Heading")
  ```claude         → st.markdown (Claude-generated scaffold text)
  ```chart          → rendered via content.charts.render(spec)
    key = value
  ```
  Plain paragraphs  → bjp("...") (user-authored text)
  ---               → st.divider()

Run:
  uv run python build_page.py
"""
from __future__ import annotations
import textwrap
from pathlib import Path

SRC  = Path(__file__).parent / "content" / "bluffers_guide.md"
DEST = Path(__file__).parent / "_pages" / "0_Bluffers_Guide.py"

# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

def parse(text: str) -> list[dict]:
    """Parse markdown into a list of block dicts."""
    blocks: list[dict] = []
    lines  = text.splitlines()
    i      = 0

    while i < len(lines):
        line = lines[i]

        # Skip HTML comments
        if line.strip().startswith("<!--"):
            while i < len(lines) and "-->" not in lines[i]:
                i += 1
            i += 1
            continue

        # H1 — skip (page title already set via st.title in the generated output)
        if line.startswith("# ") and not line.startswith("## "):
            i += 1
            continue

        # Heading
        if line.startswith("## "):
            blocks.append({"type": "heading", "text": line[3:].strip()})
            i += 1
            continue

        # Horizontal rule
        if line.strip() == "---":
            blocks.append({"type": "divider"})
            i += 1
            continue

        # ```claude block — scaffold text → st.markdown
        if line.strip() == "```claude":
            claude_lines = []
            i += 1
            while i < len(lines) and lines[i].strip() != "```":
                claude_lines.append(lines[i])
                i += 1
            i += 1  # skip closing ```
            blocks.append({"type": "markdown", "text": "\n".join(claude_lines).strip()})
            continue

        # ```chart block
        if line.strip() == "```chart":
            spec_lines = []
            i += 1
            while i < len(lines) and lines[i].strip() != "```":
                spec_lines.append(lines[i])
                i += 1
            i += 1  # skip closing ```
            spec = {}
            for sl in spec_lines:
                if "=" in sl:
                    k, _, v = sl.partition("=")
                    spec[k.strip()] = v.strip()
            blocks.append({"type": "chart", "spec": spec})
            continue

        # Blank line — skip
        if not line.strip():
            i += 1
            continue

        # Plain paragraph — user text → bjp()
        para_lines = []
        while i < len(lines) and lines[i].strip() and \
              not lines[i].startswith("## ") and \
              not lines[i].strip().startswith("```") and \
              lines[i].strip() != "---" and \
              not lines[i].strip().startswith("<!--"):
            para_lines.append(lines[i])
            i += 1
        if para_lines:
            blocks.append({"type": "bjp", "text": "\n".join(para_lines).strip()})
        continue

    return blocks


# ---------------------------------------------------------------------------
# Code generator
# ---------------------------------------------------------------------------

_CHART_COUNTER = [0]


def generate(blocks: list[dict]) -> str:
    _CHART_COUNTER[0] = 0
    lines = [
        '"""Bluffer\'s Guide to USS Conditional Indexation.',
        "",
        "AUTO-GENERATED by build_page.py — do not edit directly.",
        "Edit content/bluffers_guide.md and re-run build_page.py.",
        '"""',
        "import streamlit as st",
        "import sys",
        "from pathlib import Path",
        "",
        "sys.path.insert(0, str(Path(__file__).parent.parent))",
        "",
        "from content.charts import render",
        "from branding.branding import apply_branding",
        "",
        'apply_branding(page_title="Bluffer\'s Guide")',
        'st.title("A Bluffer\'s Guide to USS Conditional Indexation")',
        "",
    ]

    for block in blocks:
        t = block["type"]

        if t == "heading":
            lines.append(f'st.subheader({block["text"]!r})')
            lines.append("")

        elif t == "divider":
            lines.append("st.divider()")
            lines.append("")

        elif t == "markdown":
            # Claude-generated scaffold text — blockquote with label
            text = block["text"]
            text_lines = text.splitlines()
            quoted_lines = []
            for i, line in enumerate(text_lines):
                if line.strip():
                    prefix = "> *Claude AI: " if i == 0 else "> *"
                    quoted_lines.append(f"{prefix}{line}*")
                else:
                    quoted_lines.append(">")
            lines.append(f'st.markdown({chr(10).join(quoted_lines)!r})')
            lines.append("")

        elif t == "bjp":
            # User-authored text — plain markdown
            text = block["text"]
            lines.append(f'st.markdown({text!r})')
            lines.append("")

        elif t == "chart":
            _CHART_COUNTER[0] += 1
            n      = _CHART_COUNTER[0]
            spec   = block["spec"]
            caption    = spec.get("caption", f"Figure {n}.")
            toggleable = spec.pop("toggleable", "false").lower() == "true"
            spec.pop("toggleable", None)
            spec_items = ", ".join(f"{k!r}: {v!r}" for k, v in spec.items())
            if toggleable:
                lines.append(f'_nominal_{n} = st.checkbox("Show nominal £", key="nominal_{n}")')
                lines.append(f"_spec_{n} = {{{spec_items}, 'show_nominal': str(_nominal_{n}).lower()}}")
            else:
                lines.append(f"_spec_{n} = {{{spec_items}}}")
            lines.append(f"_result_{n}, _cap_{n} = render(_spec_{n})")
            lines.append(f"import pandas as _pd_{n}")
            lines.append(f"if isinstance(_result_{n}, _pd_{n}.DataFrame):")
            lines.append(f'    st.dataframe(_result_{n}, use_container_width=True)')
            lines.append(f"else:")
            lines.append(f'    st.plotly_chart(_result_{n}, use_container_width=True, key="chart_{n}")')
            lines.append(f'st.caption({caption!r})')
            lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    src_text = SRC.read_text(encoding="utf-8")
    blocks   = parse(src_text)
    code     = generate(blocks)
    DEST.write_text(code, encoding="utf-8")
    print(f"Written {DEST}  ({len(blocks)} blocks, {_CHART_COUNTER[0]} charts)")


if __name__ == "__main__":
    main()
